### PR TITLE
Fixing regex to allow leading zeros

### LINKED ISSUE #11: Properly parse decimals without leading zero
`.04` gets parsed out to `4`. Typing `.04` should be parsed the same as `0.04`.

### PR DESCRIPTION
**Pull request by jackah2**
Fixed the number parsing regex not picking up decimals with no leading zero.

Resolves #11.

### CODE REVIEW

File: src/main/java/edu/whimc/sciencetools/commands/subcommands/Validate.java [hunk 1]
```diff
@@ -166,21 +166,21 @@ public boolean commandRoutine(CommandSender sender, String[] args) {
...
 		Bukkit.getScheduler().cancelTask(validation.getTaskId());
 
 		ToolType type = validation.getType();
 
-		Pattern pat = Pattern.compile("(-?\\d+(\\.\\d+)?)");
+		Pattern pat = Pattern.compile("(-?\\d*(\\.\\d+)?)");
 		Matcher matcher = pat.matcher(event.getMessage().replace(",", ""));
 
-		if (!matcher.find()) {
+		if (!matcher.find() || matcher.group().isEmpty()) {
```
Comment (jackah2) [inline src/main/java/edu/whimc/sciencetools/commands/subcommands/Validate.java:183]: These are the main changes. The rest were automatically added with my formatter.
